### ISSUE TITLE
Read files

### ISSUE THREAD

**Issue by Siggard** [Siggard/twitter_forecast#1]
Пока простое. Учимся работать с файлами.

1. Необходимо открыть каталог clubs и в цикле пройтись по всем файлам этого каталога. 
2. Далее во вложенном цикле открыть каждый файл и пройтись по каждой строке файла. А далее уже здесь внутри пойдёт работа с twitter API используя эту ссылку.

Условно код будет выглядеть так:
```
цикл А (по файлам из каталога)
    цикл Б (по строкам из файла)
        здесь основной код => работаем со ссылкой на аккаунт, используем API, получаем ленту, парсим текст, сохраняем информацию
    конец цикла Б
конец цикла А
```

**Comment by SleepMichael** [comment]
#предлогаю заменить вхождение в каталог, вхождением в файл и пробеганием по всем строкам данного файла
open_file_clubs = open("C:\\Документы Михаила\\КОДИНГ\\GIT_MY_HUB\\clubs\\clubs_FK.txt")
#при помощи функции open прописываем путь к объекту, прописанный объект сохраняем в переменную
text = open_file_clubs.read()
#получаем содержимое файла и записываем в переменную

**Comment by Siggard** [comment]
1. Нельзя обращаться к файлу напрямую. А если его название изменится? К тому же файлы будут добавляться новые и ты при этом не должен менять код. Значит надо идти по всем файлам каталога, для этого есть специальные функции.
2. Пути должны быть относительные, а не "документы михаила\кодинг\и т.д."
3. Файл надо построчно считывать (каждая строка - это ссылка на аккаунт), почитай здесь например https://pythonworld.ru/tipy-dannyx-v-python/fajly-rabota-s-fajlami.html

**Comment by SleepMichael** [comment]
Согласен! Исправил, посмотри.
