### ISSUE TITLE
Read feed twitter accounts

### ISSUE THREAD

**Issue by Siggard** [Siggard/twitter_forecast#2]
Во втором цикле (там где мы открываем файл построчно), надо реализовать чтение ленты твитов полученного аккаунта (из текущей строки).

**Comment by SleepMichael** [comment]
допустимо ли использование написание имени в блокноте.txt  директории /clubs не в формате ссылки, а в формате имени после слеша, к примеру не https://twitter.com/pfc_cska а pfc_cska ?

**Comment by SleepMichael** [comment]
Выполнил, отправил на проверку.

**Comment by Siggard** [comment]
Отлично!
